apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: auraweb
  name: redis-pvc
  labels:
    app: redis-pvc
spec:
  storageClassName: gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
