apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: auraweb
  name: redis-deploy
  labels:
    app: redis-deploy
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: redis-pod-deploy
  template:
    metadata:
      labels:
        app: redis-pod-deploy
    spec:
      serviceAccountName: redisservice
      containers:
        - name: redis
          image: redis/redis-stack-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "64m"
              memory: "50Mi"
            limits:
              cpu: "256m"
              memory: "512Mi"
          volumeMounts:
            - name: redis-data
              mountPath: /data
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            tcpSocket:
              port: 6379
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            tcpSocket:
              port: 6379
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc
