apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: auraweb
  name: platform-deploy
  labels:
    app: platform-deploy
spec:
  selector:
    matchLabels:
      app: platform-pod-deploy
  template:
    metadata:
      labels:
        app: platform-pod-deploy
    spec:
      serviceAccountName: platformservice
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
        runAsNonRoot: true
      containers:
        - name: platform
          image: kubeprojects/platform:2.0
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3005"
            - name: DB_HOST
              value: postgres-service
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: auraweb_db
            - name: DB_USER
              value: auraweb_user
            - name: DB_PASSWORD
              value: password
            - name: RABBITMQ_URL
              value: amqp://rabbitmq-service:5672
            - name: AWS_ACCESS_KEY_ID
              value: minio
            - name: AWS_SECRET_ACCESS_KEY
              value: minio123
            - name: AWS_BUCKET_NAME
              value: mybucket
          ports:
            - containerPort: 3005
          resources:
            requests:
              cpu: "64m"
              memory: "256Mi"
            limits:
              cpu: "256m"
              memory: "512Mi"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
              drop:
                - ALL
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            httpGet:
              path: /health
              port: 3005
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            httpGet:
              path: /health
              port: 3005
