apiVersion: v1
kind: Service
metadata:
  namespace: auraweb
  name: user-auth-service
  labels:
    app: user-auth-service
spec:
  selector:
    app: user-auth-pod-deploy
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
