apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: auraweb
  name: order-payment-deploy
  labels:
    app: order-payment-deploy
spec:
  selector:
    matchLabels:
      app: order-payment-pod-deploy
  template:
    metadata:
      labels:
        app: order-payment-pod-deploy
    spec:
      serviceAccountName: order-paymentservice
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
        runAsNonRoot: true
      containers:
        - name: order-payment
          image: kubeprojects/orderpayments:1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3002"
            - name: DB_HOST
              value: postgres-service
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: auraweb_db
            - name: DB_USER
              value: auraweb_user
            - name: DB_PASSWORD
              value: password
            - name: RABBITMQ_URL
              value: amqp://rabbitmq-service:5672
            - name: STRIPE_SECRET_KEY
              value: default_stripe_key
          ports:
            - containerPort: 3002
          resources:
            requests:
              cpu: "64m"
              memory: "256Mi"
            limits:
              cpu: "256m"
              memory: "512Mi"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
              drop:
                - ALL
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            httpGet:
              path: /health
              port: 3002
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            httpGet:
              path: /health
              port: 3002
