apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: auraweb
  name: frontend-deploy
  labels:
    app: frontend-deploy
spec:
  selector:
    matchLabels:
      app: frontend-pod-deploy
  template:
    metadata:
      labels:
        app: frontend-pod-deploy
    spec:
      serviceAccountName: frontendservice
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
        runAsNonRoot: true
      containers:
        - name: frontend
          image: kubeprojects/frontend:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "64Mi"
              memory: "50m"
            limits:
              cpu: "128Mi"
              memory: "200m"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
              drop:
                - ALL
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            httpGet:
              path: /
              port: 80
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            httpGet:
              path: /
              port: 80
