apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: auraweb
  name: postgres-pvc
  labels:
    app: postgres-pvc
spec:
  storageClassName: gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
