apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: auraweb
  name: rabbitmq-deploy
  labels:
    app: rabbitmq-deploy
spec:
  selector:
    matchLabels:
      app: rabbitmq-pod-deploy
  template:
    metadata:
      labels:
        app: rabbitmq-pod-deploy
    spec:
      serviceAccountName: rabbitmqservice
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: guest
            - name: RABBITMQ_DEFAULT_PASS
              value: guest
          ports:
            - containerPort: 5672
          resources:
            requests:
              cpu: "64Mi"
              memory: "50m"
            limits:
              cpu: "256Mi"
              memory: "512Mi"
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            tcpSocket:
              port: 5672
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            tcpSocket:
              port: 5672
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: rabbitmq-pvc
