apiVersion: v1
kind: Service
metadata:
  namespace: auraweb
  name: rabbitmq-service
  labels:
    app: rabbitmq-service
spec:
  selector:
    app: rabbitmq-pod-deploy
  type: ClusterIP
  ports:
    - port: 5672
      targetPort: 5672
