apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: auraweb
  name: rabbitmq-pvc
  labels:
    app: rabbitmq-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
