apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: auraweb
  name: rabbitmq-deploy
  labels:
    app: rabbitmq-deploy
spec:
  selector:
    matchLabels:
      app: rabbitmq-pod-deploy
  template:
    metadata:
      labels:
        app: rabbitmq-pod-deploy
    spec:
      serviceAccountName: rabbitmqservice
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
        runAsNonRoot: true
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5672
          resources:
            requests:
              cpu: "64Mi"
              memory: "50m"
            limits:
              cpu: "128Mi"
              memory: "200m"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
              drop:
                - ALL
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            tcpSocket:
              port: 5672
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            tcpSocket:
              port: 5672
